name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: pip install matplotlib
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1
    - run: julia -e '
            using Pkg;
            Pkg.add(Pkg.PackageSpec(name="NodeJS"));
            using NodeJS;
            run(`$(npm_cmd()) install lunr`);
            run(`$(npm_cmd()) install cheerio`);
            Pkg.add(Pkg.PackageSpec(name="Franklin", rev="master"));
            Pkg.activate("."); Pkg.instantiate();
            using Franklin;
            optimize(minify=false, prerender=false);'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/__site
